name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      run: git clone ${{ github.event.repository.clone_url }}

    - name: Install dependencies
      run: |
        cd ${{ github.event.repository.name }}
        npm install
      
    - name: Run integration tests
      run: |
        cd ${{ github.event.repository.name }}
        npm test
